project:
  type: website
  output-dir: ../docs

website:
  title: "Quarto Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd
      - mco_book.qmd
      - mco_book_3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



